# Generated by Django 4.2 on 2024-05-07 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Artworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
